name: hello world
on: push
jobs:
  c:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        - uses: actions/checkout@v4

      - name: compile code 
        - run: cc test.c

      - run: ./a.out